# Generated by Django 5.0.3 on 2024-03-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='photo',
            field=models.ImageField(default='https://images.prewarcar.com/pics/r2w-1200x800-products/22272/1907-victor-coys-2014-4.jpg', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
